# Generated by Django 4.2.13 on 2026-06-15 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taluks', to='api.district')),
            ],
            options={
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('wb_type', models.CharField(choices=[('Lake', 'Lake'), ('Pond', 'Pond'), ('Canal', 'Canal'), ('River', 'River'), ('Kanmai', 'Kanmai')], max_length=20)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Full', 'Full'), ('Medium', 'Medium'), ('Dry', 'Dry')], default='Medium', max_length=10)),
                ('water_level', models.IntegerField(default=50, help_text='Water level as percentage')),
                ('area', models.CharField(blank=True, max_length=30)),
                ('last_inspection', models.DateField(blank=True, null=True)),
                ('next_inspection', models.DateField(blank=True, null=True)),
                ('work_status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Delayed', 'Delayed')], default='Pending', max_length=20)),
                ('reno_status', models.CharField(choices=[('Under Renovation', 'Under Renovation'), ('Renovation Complete', 'Renovation Complete'), ('Renovation Pending', 'Renovation Pending'), ('Encroachment', 'Encroachment'), ('Disappeared', 'Disappeared')], default='Renovation Pending', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taluk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_bodies', to='api.taluk')),
            ],
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Delayed', 'Delayed')], default='Pending', max_length=20)),
                ('officer', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='api.waterbody')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='water_bodies/photos/')),
                ('phase', models.CharField(choices=[('before', 'Before'), ('during', 'During'), ('after', 'After')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.waterbody')),
                ('work_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.workentry')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'District Administrator'), ('taluk', 'Taluk Officer'), ('field', 'Field Officer'), ('auditor', 'Auditor')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On leave', 'On leave'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('initials', models.CharField(blank=True, max_length=3)),
                ('taluk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taluk')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Scheduled', max_length=15)),
                ('officer', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='api.waterbody')),
            ],
        ),
        migrations.CreateModel(
            name='LocalBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lb_type', models.CharField(choices=[('Municipality', 'Municipality'), ('Town Panchayat', 'Town Panchayat'), ('Panchayat', 'Panchayat')], max_length=30)),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_bodies', to='api.taluk')),
            ],
        ),
    ]
