# Generated by Django 4.2.13 on 2026-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbody',
            name='catchment_area',
            field=models.CharField(blank=True, help_text='Catchment area in sq.km', max_length=50),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='inflow_sources',
            field=models.TextField(blank=True, help_text='Comma-separated inflow sources'),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='outflow_details',
            field=models.TextField(blank=True, help_text='Outflow destinations and type'),
        ),
    ]
