# Generated by Django 4.2.13 on 2026-06-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_waterbody_catchment_area_waterbody_inflow_sources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_entries', to='api.waterbody')),
            ],
        ),
        migrations.CreateModel(
            name='MachineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_entries', to='api.waterbody')),
            ],
        ),
        migrations.CreateModel(
            name='FundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_entries', to='api.waterbody')),
            ],
        ),
    ]
