# Generated by Django 4.2.13 on 2026-06-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_waterlevelrecord_notification_auditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutflowSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('outlet_type', models.CharField(choices=[('weir', 'Surplus weir'), ('canal', 'Irrigation canal'), ('sluice', 'Outlet sluice'), ('drain', 'Overflow drain'), ('supply', 'Water supply'), ('fisheries', 'Fisheries'), ('seepage', 'Seepage'), ('other', 'Other')], default='other', max_length=30)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('needs_repair', 'Needs repair'), ('silted', 'Silted')], default='good', max_length=20)),
                ('connected_to', models.CharField(blank=True, max_length=300)),
                ('length_km', models.FloatField(blank=True, null=True)),
                ('ayacut_acres', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflow_sources_set', to='api.waterbody')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InflowSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('catchment', 'Catchment'), ('canal', 'Canal connection'), ('river', 'River connection'), ('groundwater', 'Groundwater support'), ('sluice', 'Inlet sluice'), ('stream', 'Stream'), ('other', 'Other')], default='other', max_length=30)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('bidirectional', 'Bidirectional'), ('seasonal', 'Seasonal')], default='inflow', max_length=20)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('needs_repair', 'Needs repair'), ('silted', 'Silted')], default='good', max_length=20)),
                ('connected_to', models.CharField(blank=True, max_length=300)),
                ('length_km', models.FloatField(blank=True, null=True)),
                ('ayacut_acres', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflow_sources_set', to='api.waterbody')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
