# Generated by Django 4.2.13 on 2026-06-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_outflowsource_inflowsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbody",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="waterbody",
            name="survey_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
