# Generated by Django 4.2.13 on 2026-06-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_waterbody_address_waterbody_survey_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="taluk",
            name="division",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="localbody",
            name="lb_type",
            field=models.CharField(
                choices=[
                    ("Municipality", "Municipality"),
                    ("Town Panchayat", "Town Panchayat"),
                    ("Panchayat", "Panchayat"),
                    ("Block", "Block"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "panchayat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="api.localbody",
                    ),
                ),
            ],
        ),
    ]
