# Generated by Django 4.2.13 on 2026-06-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_taluk_division_alter_localbody_lb_type_village"),
    ]

    operations = [
        migrations.AddField(
            model_name="localbody",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="api.localbody",
            ),
        ),
    ]
