# Generated by Django 5.0.6 on 2026-06-11 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("LAKE", "Lake"), ("POND", "Pond")],
                        default="POND",
                        max_length=10,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "boundary_geojson",
                    models.TextField(
                        blank=True,
                        help_text="Optional GeoJSON polygon of the water body outline.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_RENOVATION", "Under Renovation"),
                            ("RENOVATION_COMPLETE", "Renovation Complete"),
                            ("RENOVATION_PENDING", "Renovation Pending"),
                            ("ENCROACHMENT", "Encroachment"),
                            ("DISAPPEARED", "Disappeared"),
                        ],
                        default="RENOVATION_PENDING",
                        max_length=20,
                    ),
                ),
                ("pending_reason", models.TextField(blank=True)),
                (
                    "water_source",
                    models.CharField(
                        choices=[
                            ("RAIN_WATER", "Rain Water Only"),
                            ("RIVER_CONNECTION", "River Connection"),
                            ("BOTH", "Rain Water + River Connection"),
                        ],
                        default="RAIN_WATER",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_litres",
                    models.BigIntegerField(
                        blank=True, help_text="Storage capacity in litres.", null=True
                    ),
                ),
                (
                    "area_acres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "revived_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NGO", "NGO"),
                            ("LOCAL_TEAM", "Local Team"),
                            ("GOVERNMENT", "Government"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "revived_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the NGO / local team.",
                        max_length=200,
                    ),
                ),
                (
                    "incharge_name",
                    models.CharField(
                        blank=True,
                        help_text="Free-text incharge if not a system user.",
                        max_length=200,
                    ),
                ),
                ("incharge_contact", models.CharField(blank=True, max_length=50)),
                (
                    "total_funds_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rolled up from renovation fund entries.",
                        max_digits=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_bodies",
                        to="geography.area",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_water_bodies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incharge_water_bodies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_bodies",
                        to="geography.localbody",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_bodies",
                        to="geography.village",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_bodies",
                        to="geography.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Water Body",
                "verbose_name_plural": "Water Bodies",
                "ordering": ["name"],
            },
        ),
    ]
